Remove view box
NatLabRockies/floorspace.js pull request #190
Opened 2017-08-25 18:36 UTC by bgschiller

fixes #100, #174, and #132.

This is the longer-term fix whose arrival was foretold in #184 🔮  👻 .

The main point of this PR is removing this line:
```
this.$refs.grid.setAttribute('viewBox', `0 0 ${this.max_x - this.min_x} ${this.max_y - this.min_y}`);
```
Almost everything else was removing the workarounds that were added to accommodate that line, or adding things to correct for the fact that we're now working on the scale of pixels instead of real-world-units.

That line said "scale everything inside the svg so that when I say "1" I mean "1 meter" or "1 foot", instead of "1 pixel" as would be the default. That meant:

- font sizes now needed to be scaled. "12" wasn't "12pt", it was "12m", so they were scaled down to avoid taking up the whole screen. This didn't always work, as in #100.
- When working in a small region, say, `max_x - min_x` less than 20 or so, there was a noticeable offset between where the grid was drawn, and where click events registered. This is because d3 applies a 0.5 offset when drawing axes (https://groups.google.com/forum/#!topic/d3-js/-Sw0Wdnkeko) in order to fix a rendering bug in safari. 0.5 was intended to mean '0.5pixels', but was being interpreted as '0.5 ft'.

Also in this PR, I changed the grid and polygon drawing code to update existing DOM nodes if possible, rather than destroying and creating new ones. Not sure if that actually improves things, since vue was going to do a virtual dom diff anyway. ¯\\\_(ツ)_/¯

2017-08-25 20:38 UTC, gh-23378 requested changes

2017-08-25 20:38 UTC, gh-23378 commented on src/store/modules/project/index.js
> +      spacing: 50,
let's decrease the default spacing and update our y values for when the grid loads

2017-08-25 20:38 UTC, gh-23378 commented on src/components/Grid/Grid.vue
> +    this.$refs.grid.addEventListener('reloadGridScales', this.reloadGridAndScales);
when you zoom too far out, disable the grid for performance

2017-08-25 20:38 UTC, gh-23378 commented on src/components/Grid/Grid.vue
> +      this.forceGridHide = (newTransform.k < 0.1);
oops, didn't see this. looks like we're already disabling the grid but there's something stopping it from happening

2017-08-25 20:38 UTC, gh-23378 commented on src/store/utilities/importFloorplan.js
> +  document.getElementById('svg-grid').dispatchEvent(new Event('reloadGridScales'));
having a strange effect on image imports

2017-08-27 03:41 UTC, bgschiller commented
@devKate Images are working very well now. Lots of changes, so it's probably worth another review.

2017-08-28 02:27 UTC, devKate commented
Nice! Looks good :)

2017-08-28 02:27 UTC, merged